### ISSUE TITLE
Optimize handling of dependencies in filesystem

### ISSUE THREAD

**Issue by maexbower** [Philhil/x.509Check#1]
https://github.com/Philhil/x.509Check/blob/29583799d8e5d4740cf3784d9bcfcb52a08f1e37/index.js#L13-L27

Maybe this is not the best position to do this check.
Maybe we can use the [fs.mkdtempsync()](https://nodejs.org/api/fs.html#fs_fs_mkdtempsync_prefix_options) function. This will create us a tempdir in the users temp folder and is more generic.

**Comment by Philhil** [comment]
This should be checked initial or befor uploading data. Not when requesting /
